### PR TITLE
Make dual nick colors

### PR DESCRIPTION
**Pull request by Ertew**
It would be nice to add separate nickname color to every user, probably by attach that to every displayed message with inline css attribute. 
Next, js frontend should edit (or switch) css style by option: 
- add !important tribute to display user-role nick colors or 
- remove !important to display nick colors selected for each user. 

Nick colors should be master-selected for registered users, like receive it from forum database (phpBB3 have mod for different nick colors). Also, there should be option to change user color by user during conversation, based on permissions. 

Optional, if colors settings was storage on client side, should be option to locally edit user colors i.e. mark friend's nicks to green, enemies nicks to red.

### CODE REVIEW

**Comment by Frug** [comment]
I'm not sure how you created a PR with what should be an issue, but I'm going to have to close this.

**Comment by chezinut** [comment]
hey  Ertew  you should create your own fork :)

**Comment by Ertew** [comment]
Dear Frug, i'm don't know what i'm doing here, that my first steps on GitHub. Probably clicked wrong tab. 

Dear chezinut, not at this time. First long free time was on summer holidays, that moment was good time to code anything.

**Comment by Frug** [comment]
No problem. I was drunk and have been bad about working on chat for too long.

**Pull request closed without merging**
